name: mekimeki_kakeibo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: any
  flutter_riverpod: ^1.0.3
  freezed_annotation:
  awesome_icons: ^1.1.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner:
  freezed:

flutter:

  uses-material-design: true

  assets:
    - assets/icon/

  fonts:
    - family: RoundedMPlus
      fonts:
        - asset: fonts/rounded-mplus-1p-thin.ttf
          weight: 100
        - asset: fonts/rounded-mplus-1p-light.ttf
          weight: 200
        - asset: fonts/rounded-mplus-1p-regular.ttf
          weight: 300
        - asset: fonts/rounded-mplus-1p-medium.ttf
          weight: 400
        - asset: fonts/rounded-mplus-1p-bold.ttf
          weight: 500
        - asset: fonts/rounded-mplus-1p-heavy.ttf
          weight: 600
        - asset: fonts/rounded-mplus-1p-black.ttf
          weight: 700
